server:
  port: 12379

spring:
  application:
    name: executor-springboot-sample

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8050/xxl-job-admin
    accessToken:
    executor:
      appname: executor-springboot-sample
      address:
      ip:
      port: 12479
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30